Mapping/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Mapping'


urlpatterns = [
    ######################  ACADEMIC YEAR & CLASS MAPPING URLS ##############################
    url(r'^classAcedemicyear/$', views.ClassAcedemicyear, name='classAcedemicyear'),
     url(r'^academicyearClassMapping/$', views.AcademicyearClassMapping, name='academicyearClassMapping'),
     url(r'^viewMultisectClassList/$',views.ViewMultisectClassList, name='viewMultisectClassList'),
     url(r'^class_academic_mapping/$', views.ClassAcedemicMapping, name='class_academic_mapping'),
    
     
    ######################  Class Section MAPPING URLS #######################################
        url(r'^sectionClass/$', views.SectionClass, name='sectionClass'),
        url(r'^classSectionMapping/$', views.ClassSectionMaping, name='classSectionMapping'),
        url(r'^viewMultisectSectionList/$',views.ViewMultisectSectionList, name='viewMultisectSectionList'),

        ###################### Class Teacher Mapping URLS ##########################################
        url(r'^teacherClass/$', views.TeacherClass, name='teacherClass'),
        url(r'^classTeacherMapping/$', views.ClassTeacherMaping, name='classTeacherMapping'),
        url(r'^viewMultisectTeacherList/$',views.ViewMultisectTeacherList, name='viewMultisectTeacherList'),
        
    ######################  Class Subject MAPPING URLS ##############################
        url(r'^subjectClass/$', views.ClassSubject, name='subjectClass'),
        url(r'^classSubjectMapping/$', views.ClassSubjectMaping, name='classSubjectMapping'),
        url(r'^viewMultisectSubjectList/$',views.ViewMultisectSubjectList, name='viewMultisectSubjectList'),
        
     ######################  Role User MAPPING URLS ########################################
        url(r'^roleUser/$', views.RoleUser, name='roleUser'),
        url(r'^roleUserMapping/$', views.RoleUserMapping, name='roleUserMapping'),
        url(r'^viewMultiselectUserList/$',views.ViewMultiselectUserList, name='viewMultiselectUserList'),
        
      ######################  Teacher Subject MAPPING URLS ########################################
        url(r'^teacherSubject/$', views.TeacherSubject, name='teacherSubject'),
        url(r'^teacherSubjectMapping/$', views.TeacherSubjectMapping, name='teacherSubjectMapping'),
        url(r'^viewSectionDetails/$',views.ViewSectionDetail, name='viewSectionDetails'),
        url(r'^viewMultiselectTeacherSubjectList/$',views.ViewMultiselectTeacherSubjectList, name='viewMultiselectTeacherSubjectList'),
       ###################### SUPERVISOR CLASS MAPPING URLS ########################################
        url(r'^supervisorClass/$', views.SupervisorClass, name='supervisorClass'),
        url(r'^supervisorClassMapping/$', views.SupervisorClassMapping, name='supervisorClassMapping'),
        url(r'^viewMultiselectSupervisorClassList/$',views.ViewMultiselectSupervisorClassList, name='viewMultiselectSupervisorClassList'),


    
       ######################  Student optional Subject MAPPING URLS ########################################
         url(r'^studentSubject/$', views.StudentSubject, name='studentSubject'),
         url(r'^studentSubjectMapping/$', views.StudentSubjectMapping, name='studentSubjectMapping'),
         url(r'^viewSectionDetail/$',views.ViewSectionDetails, name='viewSectionDetail'),
         url(r'^viewFilteredStudent/$',views.ViewFilteredStudent, name='viewFilteredStudent'),
 
   
   ]

Mapping/models.py
from __future__ import unicode_literals

from django.db import models
from Registration.models import *
# Create your models here.

# class AcademicyearClassRelation(models.Model):
#     class_id= models.ManyToManyField(ClassDetails)
#     academic_year = models.ForeignKey(AcademicYear, models.DO_NOTHING, blank=True, null=True)
# 
#     class Meta:
#         managed = False
#         db_table = 'academicyear_class_relation'
#         
        
# class AcademicyearClassRelation(models.Model):
#     class_id= models.ManyToManyField(ClassDetails)
#     academic_year = models.IntegerField(blank=True, null=True)
# 
#     class Meta:
#         managed = False
#         db_table = 'academicyear_class_relation'


class AcademicyearClassRelation(models.Model):
    class_id= models.ManyToManyField(ClassDetails)  # Field renamed because it was a Python reserved word.
    academic_year = models.ForeignKey(AcademicYear, models.DO_NOTHING, db_column='academic_year', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'academicyear_class_relation'
       


class AcademicyearClassRelationClassId(models.Model):
    academicyearclassrelation_id = models.IntegerField(blank=True, null=True)
    classdetails_id = models.IntegerField(blank=True, null=True)

    class Meta:
        
        managed = False
        db_table = 'academicyear_class_relation_class_id'
        

class ClassSectionMapping(models.Model):
    class_name = models.ForeignKey(ClassDetails, models.DO_NOTHING, db_column='class_name', blank=True, null=True)
    section_name = models.ManyToManyField(Sections)

    class Meta:
        managed = False
        db_table = 'class_section_mapping'


class ClassSectionMappingSectionName(models.Model):
    classsectionmapping_id = models.IntegerField(blank=True, null=True)
    sections_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'class_section_mapping_section_name'

class ClassTeacherMapping(models.Model):
    class_name = models.ForeignKey(ClassDetails, models.DO_NOTHING, db_column='class_name', blank=True, null=True)
    teacher_name = models.ManyToManyField(StaffDetails)

    class Meta:
        managed = False
        db_table = 'class_teacher_mapping'

class ClassTeacherMappingTeacherName(models.Model):
    classteachermapping_id = models.IntegerField(blank=True, null=True)
    staffdetails_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'class_teacher_mapping_teacher_name'
        


class ClassSubjectMapping(models.Model):
    class_name = models.ForeignKey(ClassDetails, models.DO_NOTHING, db_column='class_name', blank=True, null=True)
    subject_name =  models.ManyToManyField(Subject)

    class Meta:
        managed = False
        db_table = 'class_subject_mapping'
        
        
class ClassSubjectMappingSubjectName(models.Model):
    classsubjectmapping_id = models.IntegerField(blank=True, null=True)
    subject_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'class_subject_mapping_subject_name'
        
class RoleUserRelation(models.Model):
    role_name = models.ForeignKey(Role, models.DO_NOTHING, db_column='role_name', blank=True, null=True)
    user_name = models.ManyToManyField(StaffDetails)
    class Meta:
        managed = False
        db_table = 'role_user_relation'
        
class RoleUserRelationUserName(models.Model):
    roleuserrelation_id = models.IntegerField(blank=True, null=True)
    staffdetails_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'role_user_relation_user_name'
        
class TeacherSubjectRelation(models.Model):
    teacher_name = models.ForeignKey(StaffDetails, models.DO_NOTHING, db_column='teacher_name', blank=True, null=True)
    subject_name = models.ManyToManyField(Subject)
    class_name = models.IntegerField(blank=True, null=True)
    section_name = models.IntegerField(blank=True, null=True)
    assistant_teacher = models.IntegerField(blank=True, null=True)
    
    class Meta:
        managed = False
        db_table = 'teacher_subject_relation'



class TeacherSubjectRelationSubjectName(models.Model):
    teachersubjectrelation_id = models.IntegerField(blank=True, null=True)
    subject_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'teacher_subject_relation_subject_name'




class SupervisorClassRelation(models.Model):
    supervisor_name = models.ForeignKey(StaffDetails, models.DO_NOTHING, db_column='supervisor_name', blank=True, null=True)
    class_name =  models.ManyToManyField(ClassDetails)
    class Meta:
        managed = False
        db_table = 'supervisor_class_relation'

class SupervisorClassRelationClassName(models.Model):
    supervisorclassrelation_id = models.IntegerField(blank=True, null=True)
    classdetails_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'supervisor_class_relation_class_name'




class StudentOptionalSubjectMapping(models.Model):
    student_name = models.ManyToManyField(StudentDetails) 
    subject_name = models.ManyToManyField(Subject) 

    class Meta:
        managed = False
        db_table = 'student_optional_subject_mapping'


        
class StudentOptionalSubjectMappingStudentName(models.Model):
    studentoptionalsubjectmapping_id = models.IntegerField(blank=True, null=True)
    studentdetails_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'student_optional_subject_mapping_student_name'


class StudentOptionalSubjectMappingSubjectName(models.Model):
    studentoptionalsubjectmapping_id = models.IntegerField(blank=True, null=True)
    subject_id = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'student_optional_subject_mapping_subject_name'


class Religion(models.Model):
    religion_name = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'religion'
    def __unicode__(self):
        return self.religion_name
    
    
class Nationality(models.Model):
    nationality_name = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'nationality'
        
    def __unicode__(self):
        return self.nationality_name
    

Mapping/forms.py
from django import forms
import itertools
from Mapping.models import *
from Registration.models import *
from django.contrib.admin.widgets import FilteredSelectMultiple

class Newform():
    
    
    
class AcademicyearClassRelationForm(forms.ModelForm):
    AcademicYear = AcademicYear.objects.all()
    class_id = forms.ModelMultipleChoiceField(queryset=ClassDetails.objects.all(), widget=FilteredSelectMultiple("ClassDetails", is_stacked=False))
    academic_year = forms.ModelChoiceField(queryset = AcademicYear ,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))

    class Meta:
        model =AcademicyearClassRelation
        fields = ['class_id','academic_year']
 
 
 
class ClassSectionRelationForm(forms.ModelForm):
    ClassDetail = ClassDetails.objects.all()
    class_name = forms.ModelChoiceField(queryset = ClassDetail ,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))
 
    section_name = forms.ModelMultipleChoiceField(queryset=Sections.objects.all(), widget=FilteredSelectMultiple("Sections", is_stacked=False))
    class Meta:
        model = ClassSectionMapping
        fields = ['class_name','section_name']
        
        
 
class ClassSubjectMappingForm(forms.ModelForm):
    ClassDetail = ClassDetails.objects.all()
    class_name = forms.ModelChoiceField(queryset = ClassDetail ,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))
 
    subject_name = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(), widget=FilteredSelectMultiple("Subject", is_stacked=False))
    class Meta:
        model = ClassSubjectMapping
        fields = ['class_name','subject_name']
    def __init__(self, *args, **kwargs):
        
         super(ClassSubjectMappingForm, self).__init__(*args, **kwargs)
         finalDict1=[]
         queryset1 = Subject.objects.filter(type = "Mandatory")
         finalDict1.append(list(itertools.chain(queryset1)))
         cnt=0
         k=[]
         for r in finalDict1:
            if len(r)!=0:
             for s in r:
                 print (s)
                 k.append(s)
         self.fields['subject_name'].queryset = Subject.objects.filter(id__in=[r.id for r in k])
        
class RoleUserRelationForm(forms.ModelForm):
    RoleDetail = Role.objects.all()
    user_name = forms.ModelMultipleChoiceField(queryset=StaffDetails.objects.all(), widget=FilteredSelectMultiple("StaffDetails", is_stacked=False))
    role_name = forms.ModelChoiceField(queryset = RoleDetail ,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    class Meta:
        model = RoleUserRelation
        fields = ['user_name','role_name']
        
     
    def __init__(self, *args, **kwargs):
        
         super(RoleUserRelationForm, self).__init__(*args, **kwargs)
         finalDict1=[]
         queryset1 = StaffDetails.objects.filter(role_type__isnull=True)
         finalDict1.append(list(itertools.chain(queryset1)))
         cnt=0
         k=[]
         for r in finalDict1:
            if len(r)!=0:
             for s in r:
                 print (s)
                 k.append(s)
         self.fields['user_name'].queryset = StaffDetails.objects.filter(id__in=[r.id for r in k])
        
class TeacherSubjectRelationForm(forms.ModelForm):
   
    StaffDetail = StaffDetails.objects.filter(role_type = 2)   
    #teacher_name = forms.ModelChoiceField(queryset= StaffDetail,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    teacher_name = forms.ModelMultipleChoiceField(queryset=StaffDetail, widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    subject_name = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(), widget=FilteredSelectMultiple("Subject", is_stacked=False))
    assistant_teacher = forms.ModelMultipleChoiceField(queryset=StaffDetails.objects.filter(role_type=15), widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    class_name = forms.ModelMultipleChoiceField(queryset=ClassDetails.objects.all(), widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    section_name = forms.ModelMultipleChoiceField(queryset=Sections.objects.none(), widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    
    class Meta:
        model = TeacherSubjectRelation
        fields = ['subject_name','teacher_name']
        
 
class SupervisorClassRelationForm(forms.ModelForm):
    StaffDetail = StaffDetails.objects.filter(role_type = 3)  
    supervisor_name = forms.ModelChoiceField(queryset = StaffDetail ,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))
 
    class_name = forms.ModelMultipleChoiceField(queryset=ClassDetails.objects.all(), widget=FilteredSelectMultiple("ClassDetail", is_stacked=False))
    class Meta:
        model = SupervisorClassRelation
        fields = ['supervisor_name','class_name']
        
class ClassTeacherRelationForm(forms.ModelForm):
    ClassDetail = ClassDetails.objects.all()
    class_name = forms.ModelChoiceField(queryset = ClassDetail ,widget=forms.Select(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    teacher_name = forms.ModelMultipleChoiceField(queryset=StaffDetails.objects.filter(role_type=2), widget=FilteredSelectMultiple("Sections", is_stacked=False))
    
    class Meta:
        model = ClassTeacherMapping
        fields = ['class_name','teacher_name']      


class StudentOptionalSubjectMappingForm(forms.ModelForm):
    SectionDetail = Sections.objects.all()
    ReligionDetail = Religion.objects.all()
    NationalityDetail = Nationality.objects.all()
    ClassDetail = ClassDetails.objects.all()
    religion = forms.ModelMultipleChoiceField(required=False ,queryset = ReligionDetail ,widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    nationality = forms.ModelMultipleChoiceField(required=False ,queryset = NationalityDetail ,widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
  
    class_name = forms.ModelMultipleChoiceField(required=False , queryset = ClassDetail ,widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    section_name = forms.ModelMultipleChoiceField(required=False ,queryset = SectionDetail ,widget=forms.SelectMultiple(attrs={'class':'form-control' , 'autocomplete': 'off'}))
  
    subject_name = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(), widget=FilteredSelectMultiple("Subject", is_stacked=False))
 
    student_name = forms.ModelMultipleChoiceField(queryset=StudentDetails.objects.all(), widget=FilteredSelectMultiple("StudentDetails", is_stacked=False))
    class Meta:
        model = StudentOptionalSubjectMapping
        fields = ['subject_name','student_name']
        
    def __init__(self, *args, **kwargs):
        
         super(StudentOptionalSubjectMappingForm, self).__init__(*args, **kwargs)
         finalDict1=[]
         queryset1 = Subject.objects.filter(type = "Optional")
         finalDict1.append(list(itertools.chain(queryset1)))
         cnt=0
         k=[]
         for r in finalDict1:
            if len(r)!=0:
             for s in r:
                 print (s)
                 k.append(s)
         self.fields['subject_name'].queryset = Subject.objects.filter(id__in=[r.id for r in k])
              
    
    

Mapping/templates/academic_mapping_view.html
{% extends "index.html" %}
{% load staticfiles %}
       

 {%block styleBlock%}
<!-- BEGIN GLOBAL MANDATORY STYLES -->
      
        <link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
        
       
         </head>
    <!-- END HEAD -->
    
   
    {%endblock%}
    
{%block ScriptBlock%} 

<script>
window.setTimeout(function() 
{
    $(".alert").fadeTo(500, 0).slideUp(500, function()
    {
        $(this).remove(); 
    });
}, 4000);

</script>

{%endblock%}

 {% block content %}
<div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <i class="icon-home"></i>
                                <a href="{% url 'home' %}">Home</a>
                                <i class="fa fa-angle-right"></i>
                            </li>
                            <li>
                                <span>Mapping</span>
                            </li>
                        </ul>
</div>
 

{% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;" >{{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    </div>
{% endfor %}

                            <!-- BEGIN VALIDATION STATES-->
                    <div class="portlet light ">
                           <div class="portlet-title">
                                <div class="caption">
                                    <i class="icon-bubble font-green-sharp"></i>
                                    <span class="caption-subject font-green-sharp sbold">Mapping</span>
                                </div>
                          
                            </div>

                       

                        <div class="portlet-body">


                            <div class="tiles">
                               
                                <a href="{% url 'Mapping:classAcedemicyear' %}">
                               <div class="tile double bg-red-sunglo">
                                    <div class="tile-body">
                                        <i class="icon-calendar"></i>
                                        <!--<img src="../assets/pages/media/profile/photo1.jpg" alt="">-->
                                       <!-- <h4>Announcements</h4>
                                        <p> Easily style icon color, size, shadow, and anything that's possible with CSS. </p>-->
                                    </div>
                                    <div class="tile-object">
                                        <div class="name"> <h4>ClassAcademicMapping<h4></div>
                                        <!--<div class="number"> 24 Jan 2013 </div>-->
                                    </div>
                                </div>
                                
                              </a>

                               <a href="{% url 'Mapping:sectionClass' %}">
                               <div class="tile double bg-green-turquoise">
                                    <div class="tile-body">
                                        <i class="icon-calendar"></i>
                                        <!--<img src="../assets/pages/media/profile/photo1.jpg" alt="">-->
                                       <!-- <h4>Announcements</h4>
                                        <p> Easily style icon color, size, shadow, and anything that's possible with CSS. </p>-->
                                    </div>
                                    <div class="tile-object">
                                        <div class="name"> <h4>SectionClassMapping<h4></div>
                                        <!--<div class="number"> 24 Jan 2013 </div>-->
                                    </div>
                                </div>
                                
                              </a>

                               <a href="{% url 'Mapping:subjectClass' %}">
                                <div class="tile double bg-yellow-lemon">
                                    <div class="tile-body">
                                        <i class="icon-calendar"></i>
                                        <!--<img src="../assets/pages/media/profile/photo1.jpg" alt="">-->
                                       <!-- <h4>Announcements</h4>
                                        <p> Easily style icon color, size, shadow, and anything that's possible with CSS. </p>-->
                                    </div>
                                    <div class="tile-object">
                                        <div class="name"> <h4>SubjectClassMapping<h4></div>
                                        <!--<div class="number"> 24 Jan 2013 </div>-->
                                    </div>
                                </div>
                                
                              </a>

                               <a href="{% url 'Mapping:roleUser' %}">
                                <div class="tile double-down bg-purple-intense" style="height: 135px !important;width: 280px !important;">
                                    <div class="tile-body">
                                        <i class="icon-calendar"></i>
                                        <!--<img src="../assets/pages/media/profile/photo1.jpg" alt="">-->
                                       <!-- <h4>Announcements</h4>
                                        <p> Easily style icon color, size, shadow, and anything that's possible with CSS. </p>-->
                                    </div>
                                    <div class="tile-object">
                                        <div class="name"> <h4>RoleUSerMapping<h4></div>
                                        <!--<div class="number"> 24 Jan 2013 </div>-->
                                    </div>
                                </div>
                                
                              </a>

                             
                               
                          
                            </div>
                        </div>
                    </div>
                            <!-- END VALIDATION STATES-->
                     
                      
         {% endblock %}           
                        

Mapping/templates/role_user_mapping.html
{% extends "index.html" %}

<html lang="">

    
         {%block styleBlock%}
     <style>
     table ,tr td{
    border:1px solid red
}
tbody {
    display:block;
    height:184px;
    overflow:auto;
}
thead, tbody tr {
    display:table;
    width:100%;
    table-layout:fixed;/* even columns width , fix width of table too*/
}
thead {
    width: calc( 100% - 1em )/* scrollbar is average 1em/16px width, remove it from thead width */
}
table {
    width:400px;
}
     </style>
        {%endblock%}
 {%block ScriptBlock%}
<script>
window.onload = function() {
	  //YOUR JQUERY CODE
	$(document).ready(function() {
		console.log("hiiii")
		
		$("#id_role_name").change(function() {
			
			 
		       
					console.log("in id_role_name year ajax")
					role_name = document.getElementById("id_role_name").value
					console.log(role_name)		
							
					var url = '/school/viewMultiselectUserList/';
					viewMultiselectUserList(url,role_name)
				});
		
		

		
		 $('#id_user_name').multiSelect({
		      afterSelect: function(values){
		        //alert("Select value: "+values);
		      },
		      afterDeselect: function(values){
		        //alert("Deselect value: "+values);
		      }
		    }); 
		
	});
	function viewMultiselectUserList(url,role_name) {
		 
		 
	      
		$.ajax({
			url : url,
			type : "GET",
			data : {
				role_name : role_name
			},
		})


		.done(
				function(data) {
					console.log(data)
					$('.user').empty();
					$('.ms-selectable .ms-list li').show();
					$('.ms-list li').each(function(i){
					    value2 = $(this).text();
					    
					    for (var i = 0; i < data.length; i++) {
							
							
					    	if (data[i].email == value2)
					    		
					    		{
					    		
					    		if($(this).text(value2)){
					    			$(this).hide();
					    		}
					    		
					    		
					    		}
							
						}

					   
					});
					
					for (var i = 0; i < data.length; i++) {
						
						
						$(".user").append('<tr><td>' + data[i].email + '</td></tr>');	
						
					}


				});
	}
	
	}
</script>
{%endblock%}  
{% block content %}
<body>
 

<div class="page-bar" style="margin-bottom: 1px;">
                        <ul class="page-breadcrumb">
                            <li>
                                <i class="icon-home"></i>
                                <a href="{% url 'Registration:home' %}">Home</a> 
                                <i class="fa fa-angle-right"></i>
                            </li>
                            <li>
                                
                                <a href="{% url 'Registration:manage_details' %}">Manage Users</a>
                                <i class="fa fa-angle-right"></i>
                            </li>
                            
                            <li>
                                <span>Role/User Mapping</span>
                            </li>
                        </ul>
                        
                    </div> 



    <div class="portlet light portlet-fit portlet-form ">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-settings font-red"></i>
                                        <span class="caption-subject font-red sbold uppercase">Role & User Mapping</span>
                                    </div>
                                   
                                </div>
                                <div class="portlet-body">
                                
                                
                                    <!-- BEGIN FORM-->
                                      <form  method="post" action="{% url 'Mapping:roleUserMapping' %}">
				{% csrf_token %}
                                        <div class="form-body">
                                            
                                            <div class="row">
                                            <div class="">
                                          
                                                <label class="col-md-2 control-label" style="width: 130px;">Role:
                                                   
                                                </label>
                                                <div class="col-md-4">
                                                   {{ RoleUserRelationForm.role_name }} </div>
                                            </div>
                                            
                                            <div class="">
                                                <button type="submit"  id="mapping" class="btn blue btn-block" style="width:200px;">
		Mapping </button>
                                            </div>
                                            </div>
                                            
                                          <div class="col-md-6" style="margin-top: 5%;">
                                            <div class="row " id="academic"  style=" margin-top: 4%;">                                       
                                              {{ RoleUserRelationForm.user_name }}
                                             
                                          
                                            </div>
                                            </div>
                                            <div class="col-md-6" style="margin-top: 5%;">
                            <!-- BEGIN BORDERED TABLE PORTLET-->
                            <div class="portlet light portlet-fit ">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-bubble font-dark"></i>
                                        <span class="caption-subject font-dark bold uppercase">Mapped Users</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body">
                                    <div class="table-scrollable">
                                        <table class="user table table-bordered table-hover" style="height:10px;">
                                            <thead>
                                                <tr>
                                                    <th> Please Select Role First </th>
                                                    
                                                </tr>
                                            </thead>
                                           
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <!-- END BORDERED TABLE PORTLET-->
                        </div>
                                            
                                       
                                            
                                            
                               
                               
                                </div>
                            </div>
                                    </form>
                                    <!-- END FORM-->
                                </div>
                                </html>
 
  
                                
                                {% endblock %}    
                            </div>